### ISSUE TITLE
역대 운영진 추가 등 페이지 전반적인 개편

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/with_website#16]
## Todo
- 페이지 추가
  - [x] FAQ를 별도 페이지로 분리하고 '소개' 하위로 추가
  - [x] `managers` 페이지 추가
  - [x] 로딩 속도가 오래 걸리는 원인이었던 캘린더 페이지를 별도 페이지로 분리
- 디자인 수정
  - [x] 모바일 페이지일 경우 상단 navi bar 테마 dark로 변경되도록 함
  - [x] 로그인했을때의 포인트 색상 검정/흰색 배경 모두에서 잘 보이도록 변경
- 운영진 페이지 보강
  - [x] 기존에 없던 운영진 직책 `models`에 추가
  - [x] 파악된 운영진들 정보 입력
- [x] 페이지 내부 메뉴 추가
- [x] 페이지 탭 title 변경
- 기타
  - [x] `base`에 GA 추가
  - [x] navi 메뉴에 '소개' 추가
