### ISSUE TITLE
봉사&행사 이벤트 규격화

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/with_website#28]
## todo
- [ ] 지나간 이벤트 참석자 등 정리(빠진 것 확인)
- [ ] model에 subtitle 추가
- [ ] event 정보를 subtitle 활용하여 규격화할 기준 잡기
- [ ] 기준에 따라 규격화 작업 수행
